# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents : write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: è¯»å–ä»“åº“å†…å®¹ ğŸ§
      uses: actions/checkout@v4

    - name: ä½¿ç”¨ Node.js ğŸ“
      uses: actions/setup-node@v4
      with:
        node-version: '16.18.1'

    - name: å®‰è£…ä¾èµ– ğŸ› 
      run: 
        npm install
        npm ci

    - name: é¡¹ç›®æ‰“åŒ… ğŸ”§
      run: npm run build
    
    - name: éƒ¨ç½² ğŸš€
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist # The folder the action should deploy.